"""Phase 0 reconnaissance: enumerate NWAC products on the public API and document shapes."""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from statistics import median

import httpx

ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw" / "recon"
DOCS_PATH = ROOT / "docs" / "api_exploration.md"
USER_AGENT = "NWAC-Daily-Summary/0.1 (amaslov85@gmail.com)"
BASE_URL = "https://api.avalanche.org/v2/public"


def parse_ts(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def field_summary(value: object, depth: int = 0) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, str):
        return "string (HTML)" if "<" in value and ">" in value else "string"
    if isinstance(value, list):
        if not value:
            return "list (empty)"
        return f"list[{field_summary(value[0], depth + 1)}]"
    if isinstance(value, dict):
        if depth >= 1:
            return "object"
        keys = ", ".join(value.keys())
        return f"object({keys})"
    return type(value).__name__


def main() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)

    headers = {"User-Agent": USER_AGENT, "Accept": "application/json"}
    with httpx.Client(headers=headers, timeout=60.0) as client:
        resp = client.get(f"{BASE_URL}/products?avalanche_center_id=NWAC")
        resp.raise_for_status()
        products: list[dict] = resp.json()

        (RAW_DIR / "products_list.json").write_text(json.dumps(products, indent=2))

        type_counts: Counter[str] = Counter(p["product_type"] for p in products)
        zones_by_type: dict[str, set[tuple[int, str]]] = defaultdict(set)
        all_zones: dict[int, dict] = {}
        for p in products:
            for z in p.get("forecast_zone") or []:
                zones_by_type[p["product_type"]].add((z["id"], z["name"]))
                all_zones[z["id"]] = z

        cadence: dict[str, dict] = {}
        for ptype in type_counts:
            times = sorted(
                p["published_time"]
                for p in products
                if p["product_type"] == ptype and p.get("published_time")
            )
            entry: dict = {
                "first": times[0] if times else None,
                "last": times[-1] if times else None,
                "count": len(times),
            }
            if len(times) >= 2:
                deltas = [
                    (parse_ts(times[i + 1]) - parse_ts(times[i])).total_seconds() / 3600
                    for i in range(len(times) - 1)
                ]
                entry["median_gap_hours"] = round(median(deltas), 1)
            cadence[ptype] = entry

        samples: dict[str, dict] = {}
        for ptype in type_counts:
            sample = next(p for p in products if p["product_type"] == ptype)
            detail_resp = client.get(f"{BASE_URL}/product/{sample['id']}")
            detail_resp.raise_for_status()
            detail = detail_resp.json()
            (RAW_DIR / f"{ptype}_sample_{sample['id']}.json").write_text(
                json.dumps(detail, indent=2)
            )
            samples[ptype] = detail

    write_report(products, type_counts, all_zones, cadence, samples)
    print(f"Records fetched: {len(products)}")
    print(f"Product types: {dict(type_counts)}")
    print(f"Raw dumps written to: {RAW_DIR}")
    print(f"Report written to: {DOCS_PATH}")


def write_report(
    products: list[dict],
    type_counts: Counter[str],
    all_zones: dict[int, dict],
    cadence: dict[str, dict],
    samples: dict[str, dict],
) -> None:
    lines: list[str] = []
    lines.append("# NWAC API Exploration")
    lines.append("")
    lines.append(f"Generated by `scripts/api_recon.py`. Total records returned: {len(products)}.")
    lines.append("")

    lines.append("## Endpoints")
    lines.append("")
    lines.append(f"- List: `GET {BASE_URL}/products?avalanche_center_id=NWAC`")
    lines.append(f"- Detail: `GET {BASE_URL}/product/{{id}}`")
    lines.append(f"- User-Agent: `{USER_AGENT}`")
    lines.append("")

    lines.append("## Product types")
    lines.append("")
    lines.append(
        "| product_type | count | first published | last published | "
        "median gap (hours) | sample id |"
    )
    lines.append("|---|---:|---|---|---:|---:|")
    for ptype, count in type_counts.most_common():
        c = cadence.get(ptype, {})
        sample_id = samples.get(ptype, {}).get("id", "")
        gap = c.get("median_gap_hours", "")
        lines.append(
            f"| `{ptype}` | {count} | {c.get('first', '')} | "
            f"{c.get('last', '')} | {gap} | {sample_id} |"
        )
    lines.append("")

    lines.append("## Zones")
    lines.append("")
    lines.append("Zone catalog from `forecast_zone[]` records (NWAC avalanche zones).")
    lines.append("")
    lines.append("| zone id | name | url |")
    lines.append("|---:|---|---|")
    for zid in sorted(all_zones):
        z = all_zones[zid]
        lines.append(f"| {zid} | {z['name']} | {z.get('url', '')} |")
    lines.append("")

    forecast = samples.get("forecast")
    if forecast:
        lines.append("## Forecast schema (from sample detail)")
        lines.append("")
        lines.append(
            f"Sample id: `{forecast['id']}`. Saved at "
            f"`data/raw/recon/forecast_sample_{forecast['id']}.json`."
        )
        lines.append("")
        lines.append("### Top-level fields")
        lines.append("")
        narrative = {"bottom_line", "hazard_discussion", "weather_discussion", "announcement"}
        structured = {
            "danger",
            "forecast_avalanche_problems",
            "forecast_zone",
            "media",
            "weather_data",
            "avalanche_center",
        }
        meta = {
            "id",
            "published_time",
            "expires_time",
            "created_at",
            "updated_at",
            "author",
            "product_type",
            "status",
        }
        lines.append("| field | type | render policy |")
        lines.append("|---|---|---|")
        for k, v in forecast.items():
            if k in narrative:
                policy = "narrative, render verbatim"
            elif k in structured:
                policy = "structured"
            elif k in meta:
                policy = "metadata"
            else:
                policy = "unknown, classify before render"
            lines.append(f"| `{k}` | {field_summary(v)} | {policy} |")
        lines.append("")

        problems = forecast.get("forecast_avalanche_problems") or []
        if problems:
            lines.append("### `forecast_avalanche_problems[]` element fields")
            lines.append("")
            lines.append("| field | type |")
            lines.append("|---|---|")
            for k, v in problems[0].items():
                lines.append(f"| `{k}` | {field_summary(v)} |")
            lines.append("")

        danger = forecast.get("danger") or []
        if danger:
            lines.append("### `danger[]` element fields")
            lines.append("")
            lines.append("| field | type |")
            lines.append("|---|---|")
            for k, v in danger[0].items():
                lines.append(f"| `{k}` | {field_summary(v)} |")
            lines.append("")

    lines.append("## Mountain weather availability")
    lines.append("")
    weather_types = [t for t in type_counts if "weather" in t.lower()]
    if weather_types:
        lines.append(
            "Mountain weather IS available on this endpoint as: "
            + ", ".join(f"`{t}`" for t in weather_types)
            + "."
        )
    else:
        lines.append(
            "Mountain weather is NOT exposed via `/v2/public/products?avalanche_center_id=NWAC`."
        )
        lines.append("")
        lines.append("Phase 2 fallback options to investigate before implementation:")
        lines.append("")
        lines.append(
            "- The NWAC mountain weather page (https://www.nwac.us/mountain-weather-forecast/) "
            "likely renders prose from a separate backend route. Inspect network calls."
        )
        lines.append(
            "- The avalanche.org product schema may expose mountain weather under a different "
            "filter. Try variants like "
            "`/v2/public/products?avalanche_center_id=NWAC&product_type=mountain_weather`."
        )
        lines.append(
            "- If no public endpoint exists, scrape the rendered HTML and treat the result as a "
            "verbatim narrative product."
        )
    lines.append("")

    lines.append("## Raw payloads")
    lines.append("")
    lines.append("All raw JSON dumps are gitignored under `data/raw/recon/`.")
    lines.append("")
    lines.append("- `products_list.json`: full list response")
    for ptype in type_counts:
        sample_id = samples[ptype]["id"]
        lines.append(
            f"- `{ptype}_sample_{sample_id}.json`: detail for one record of type `{ptype}`"
        )
    lines.append("")

    DOCS_PATH.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
